# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FrameLabel = QtWidgets.QLabel(self.centralwidget)
        self.FrameLabel.setEnabled(True)
        self.FrameLabel.setGeometry(QtCore.QRect(220, 30, 640, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.FrameLabel.sizePolicy().hasHeightForWidth())
        self.FrameLabel.setSizePolicy(sizePolicy)
        self.FrameLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.FrameLabel.setMaximumSize(QtCore.QSize(640, 16777215))
        self.FrameLabel.setStyleSheet("background:black;")
        self.FrameLabel.setText("")
        self.FrameLabel.setScaledContents(False)
        self.FrameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FrameLabel.setOpenExternalLinks(False)
        self.FrameLabel.setObjectName("FrameLabel")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 30, 191, 31))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.attendance_people = QtWidgets.QGroupBox(self.centralwidget)
        self.attendance_people.setGeometry(QtCore.QRect(10, 240, 91, 31))
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        font.setPointSize(16)
        font.setItalic(False)
        self.attendance_people.setFont(font)
        self.attendance_people.setAlignment(QtCore.Qt.AlignCenter)
        self.attendance_people.setFlat(True)
        self.attendance_people.setObjectName("attendance_people")
        self.system_name = QtWidgets.QLabel(self.centralwidget)
        self.system_name.setGeometry(QtCore.QRect(400, 0, 231, 21))
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.system_name.setFont(font)
        self.system_name.setObjectName("system_name")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 191, 99))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.loadInButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadInButton.setObjectName("loadInButton")
        self.gridLayout.addWidget(self.loadInButton, 2, 0, 1, 1)
        self.batchRegisterButton = QtWidgets.QPushButton(self.layoutWidget)
        self.batchRegisterButton.setObjectName("batchRegisterButton")
        self.gridLayout.addWidget(self.batchRegisterButton, 1, 1, 1, 1)
        self.registerButton = QtWidgets.QPushButton(self.layoutWidget)
        self.registerButton.setObjectName("registerButton")
        self.gridLayout.addWidget(self.registerButton, 1, 0, 1, 1)
        self.loadOutButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadOutButton.setObjectName("loadOutButton")
        self.gridLayout.addWidget(self.loadOutButton, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 70, 191, 62))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.teacher_name = QtWidgets.QLabel(self.layoutWidget1)
        self.teacher_name.setObjectName("teacher_name")
        self.gridLayout_2.addWidget(self.teacher_name, 0, 0, 1, 1)
        self.teacherEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.teacherEdit.setObjectName("teacherEdit")
        self.gridLayout_2.addWidget(self.teacherEdit, 0, 1, 1, 1)
        self.classroom_name = QtWidgets.QLabel(self.layoutWidget1)
        self.classroom_name.setObjectName("classroom_name")
        self.gridLayout_2.addWidget(self.classroom_name, 1, 0, 1, 1)
        self.classEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.classEdit.setObjectName("classEdit")
        self.gridLayout_2.addWidget(self.classEdit, 1, 1, 1, 1)
        self.attendance_people_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.attendance_people_text.setGeometry(QtCore.QRect(10, 270, 201, 141))
        self.attendance_people_text.setObjectName("attendance_people_text")
        self.push_attend = QtWidgets.QPushButton(self.centralwidget)
        self.push_attend.setGeometry(QtCore.QRect(120, 240, 91, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.push_attend.setFont(font)
        self.push_attend.setObjectName("push_attend")
        self.absence_people = QtWidgets.QGroupBox(self.centralwidget)
        self.absence_people.setGeometry(QtCore.QRect(10, 410, 91, 31))
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        font.setPointSize(16)
        font.setItalic(False)
        self.absence_people.setFont(font)
        self.absence_people.setAlignment(QtCore.Qt.AlignCenter)
        self.absence_people.setFlat(True)
        self.absence_people.setObjectName("absence_people")
        self.absence_people_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.absence_people_text.setGeometry(QtCore.QRect(10, 440, 201, 121))
        self.absence_people_text.setObjectName("absence_people_text")
        self.system_setting = QtWidgets.QGroupBox(self.centralwidget)
        self.system_setting.setGeometry(QtCore.QRect(870, 30, 231, 101))
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        font.setItalic(False)
        self.system_setting.setFont(font)
        self.system_setting.setObjectName("system_setting")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.system_setting)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CameraCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        font.setPointSize(10)
        self.CameraCheckBox.setFont(font)
        self.CameraCheckBox.setTristate(False)
        self.CameraCheckBox.setObjectName("CameraCheckBox")
        self.gridLayout_4.addWidget(self.CameraCheckBox, 0, 1, 1, 1)
        self.CameraButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CameraButton.setFont(font)
        self.CameraButton.setObjectName("CameraButton")
        self.gridLayout_4.addWidget(self.CameraButton, 0, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.system_setting)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 211, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tolerancelabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tolerancelabel.setFont(font)
        self.tolerancelabel.setObjectName("tolerancelabel")
        self.gridLayout_3.addWidget(self.tolerancelabel, 0, 0, 1, 1)
        self.toleranceSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.toleranceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.toleranceSlider.setObjectName("toleranceSlider")
        self.gridLayout_3.addWidget(self.toleranceSlider, 0, 1, 1, 1)
        self.valueLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.valueLabel.setFont(font)
        self.valueLabel.setObjectName("valueLabel")
        self.gridLayout_3.addWidget(self.valueLabel, 0, 2, 1, 1)
        self.gridLayoutWidget_2.raise_()
        self.gridLayoutWidget.raise_()
        self.instruction = QtWidgets.QGroupBox(self.centralwidget)
        self.instruction.setGeometry(QtCore.QRect(870, 210, 251, 121))
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        self.instruction.setFont(font)
        self.instruction.setObjectName("instruction")
        self.instruction_box = QtWidgets.QTextBrowser(self.instruction)
        self.instruction_box.setGeometry(QtCore.QRect(10, 20, 231, 91))
        self.instruction_box.setObjectName("instruction_box")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(880, 340, 231, 221))
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.log_box = QtWidgets.QTextBrowser(self.groupBox)
        self.log_box.setGeometry(QtCore.QRect(0, 20, 231, 211))
        self.log_box.setObjectName("log_box")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(870, 140, 211, 71))
        font = QtGui.QFont()
        font.setFamily("AR PL UKai CN")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.dbButton = QtWidgets.QPushButton(self.groupBox_2)
        self.dbButton.setGeometry(QtCore.QRect(30, 30, 97, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dbButton.setFont(font)
        self.dbButton.setObjectName("dbButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.attendance_people.setTitle(_translate("MainWindow", "签到人员"))
        self.system_name.setText(_translate("MainWindow", "暨南大学课堂签到系统"))
        self.loadInButton.setText(_translate("MainWindow", "导入"))
        self.batchRegisterButton.setText(_translate("MainWindow", "批量注册"))
        self.registerButton.setText(_translate("MainWindow", "注册"))
        self.loadOutButton.setText(_translate("MainWindow", "导出"))
        self.label.setText(_translate("MainWindow", "学生通道："))
        self.teacher_name.setText(_translate("MainWindow", "任课老师"))
        self.classroom_name.setText(_translate("MainWindow", "上课教室"))
        self.push_attend.setText(_translate("MainWindow", "签到"))
        self.absence_people.setTitle(_translate("MainWindow", "缺勤人员"))
        self.system_setting.setTitle(_translate("MainWindow", "系统设置"))
        self.CameraCheckBox.setText(_translate("MainWindow", "外置相机"))
        self.CameraButton.setText(_translate("MainWindow", "开启摄像头"))
        self.tolerancelabel.setText(_translate("MainWindow", "容错率"))
        self.valueLabel.setText(_translate("MainWindow", "00"))
        self.instruction.setTitle(_translate("MainWindow", "使用说明"))
        self.instruction_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'AR PL UKai CN\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.每次请使用单脸进行注册</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "日志"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据库"))
        self.dbButton.setText(_translate("MainWindow", "数据库操作"))

